version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "123456"
    networks:
      - pfa-net
    volumes:
      - type: bind
        source: ./data
        target: /root/data

  pfa:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /home/dev/pfa
    tty: true
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - pfa-net

networks:
  pfa-net: